[package]
name = "user_contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "20.5.0"

# Optional direct dependency, just in case
getrandom = { version = "0.2", features = ["js"] }

[features]
default = []

